stages:
  - test  # Определяем стадию "test"

test-job:  # Задача для стадии test
  stage: test
  script:
    - echo "Testing project! This is CI/CD pipeline!"
  tags:
    - docker  # Тег для выбора раннера
